ci:
    skip: [uv-lock]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
        args: [--maxkb=25]
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.7
    hooks:
    -   id: ruff-check
    -   id: ruff-format
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.13
    hooks:
    -   id: uv-lock
-   repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
    -   id: mdformat
        additional_dependencies:
        - mdformat-gfm
        - mdformat-black
        args: [--wrap, "88"]
-   repo: https://github.com/crate-ci/typos
    rev: v1.49.0
    hooks:
    -   id: typos
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
    # -   id: identity  # Prints all files passed to pre-commits. Debugging.
