coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    project:
      default:
        threshold: 1%

ignore:
  - ".tox/**/*"
  - "setup.py"
  - "versioneer.py"
  - "src/pytask_stata/_version.py"
