name: pytask-stata
channels:
  - conda-forge
  - pytask
dependencies:
  - python
  - pip

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >= 0.0.8

  # Misc
  - black
  - bumpversion
  - jupyterlab
  - pdbpp
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda
