name: pytask-stata

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.7
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - pytask >=0.3
  - pytask-parallel >=0.3

  # Misc
  - black
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda

  - pip:
    - -e .
