name: pytask-stata

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.6
  - pip
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >=0.1.0
  - pytask-parallel >=0.0.9

  # Misc
  - black
  - bumpversion
  - jupyterlab
  - pdbpp
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda
