name: pytask-stata

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.8
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - pytask <0.4
  - pytask-parallel <0.4

  # Misc
  - black
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda

  - pip:
    - -e .
