name: pytask-stata

channels:
  - conda-forge

dependencies:
  - python
  - pip

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >=0.0.9
  - pytask-parallel >=0.0.4

  # Misc
  - black
  - bumpversion
  - jupyterlab
  - pdbpp
  - pre-commit
  - pytest-cov
  - pytest-xdist
  - tox-conda
